"use client";

import { FormEvent, MouseEvent, useEffect, useMemo, useState } from "react";

type View = "home" | "listing" | "product" | "cart" | "checkout" | "confirmation";
type Cart = Record<string, number>;
type Product = { id: string; name: string; price: number; oldPrice?: number; category: "Living" | "Bedroom" | "Dining" | "Office"; type: string; image: string; badge?: string; saving?: string; lead: string; dimensions: string; material: string; colour: string; warranty: string };
const asset = (name: string) => `/assets/furniture/${name}`;

const products: Product[] = [
  { id: "shiloah", name: "Shiloah 3+2 seater PU leather sofa lounge set - brown", price: 4849, oldPrice: 5999, category: "Living", type: "Sofas", image: asset("shiloah.png"), badge: "SALE", saving: "Save $1,150", lead: "A generously proportioned two-piece lounge suite with supportive high backs and classic rolled arms, designed for relaxed family living.", dimensions: "3 seater: 2300(W) × 900(H) × 850(D) mm; 2 seater: 1700(W) × 900(H) × 850(D) mm", material: "Durable PU leather upholstery, hardwood and engineered timber frame, high-resilience foam", colour: "Warm brown", warranty: "5-year structural warranty; 2-year upholstery warranty" },
  { id: "sonoma", name: "Sonoma 3 seater sofa", price: 1999, category: "Living", type: "Sofas", image: asset("sonoma.jpg"), lead: "A clean-lined three-seater with soft cushioning and a compact profile that suits modern living spaces.", dimensions: "2180(W) × 860(H) × 920(D) mm", material: "Top-grain leather seating, timber frame and high-density foam", colour: "Tan", warranty: "5-year structural warranty" },
  { id: "rhianne", name: "Rhianne fabric upholstered accent chair - beige", price: 999, oldPrice: 1200, category: "Living", type: "Chairs", image: asset("rhianne.png"), badge: "SALE", saving: "Save $201", lead: "A sculptural wingback chair with deep channel detailing, supportive cushioning and a refined neutral finish.", dimensions: "820(W) × 1120(H) × 880(D) mm", material: "Textured woven fabric, solid timber legs and foam cushioning", colour: "Beige", warranty: "3-year structural warranty" },
  { id: "alvarado", name: "Alvarado (Aussie made) highline bookcase", price: 1999, category: "Office", type: "Storage", image: asset("alvarado.png"), lead: "An Australian-made highline bookcase with adjustable shelving and timeless timber detailing for living or office storage.", dimensions: "980(W) × 2100(H) × 360(D) mm", material: "Australian plantation timber and timber veneer", colour: "Natural oak", warranty: "10-year structural warranty" },
  { id: "mikey", name: "Mikey sofa fabric lounge suite 3+1+1", price: 4999, oldPrice: 5999, category: "Living", type: "Sofas", image: asset("mikey.png"), badge: "SALE", saving: "Save $1,000", lead: "A coordinated three-piece suite with traditional curves, supportive seats and hard-wearing family-friendly fabric.", dimensions: "3 seater: 2200(W) × 940(H) × 930(D) mm; chair: 980(W) × 940(H) × 930(D) mm", material: "Woven fabric, kiln-dried timber frame and pocket-spring seating", colour: "Sand", warranty: "5-year structural warranty" },
  { id: "tribeca", name: "Tribeca 3 seater leatherette sofa - black", price: 1599, category: "Living", type: "Sofas", image: asset("tribeca.png"), lead: "A tailored three-seater with deep button tufting and a compact silhouette inspired by classic club seating.", dimensions: "2050(W) × 790(H) × 880(D) mm", material: "Premium leatherette, solid timber legs and high-density foam", colour: "Black", warranty: "3-year structural warranty" },
  { id: "finlay", name: "Finlay 4 seater fabric lounge suite - grey", price: 2599, category: "Living", type: "Sofas", image: asset("finlay.png"), lead: "A spacious four-seater with broad arms and deep, resilient cushioning for everyday family comfort.", dimensions: "2780(W) × 850(H) × 980(D) mm", material: "Performance fabric, engineered timber frame and fibre-wrapped foam", colour: "Cool grey", warranty: "5-year structural warranty" },
  { id: "yemina", name: "Yemina fabric corner sofa bed with pull out storage - grey", price: 3999, oldPrice: 4999, category: "Living", type: "Sofa beds", image: asset("yemina.png"), badge: "SALE", saving: "Save $1,000", lead: "A versatile corner lounge that converts to a guest bed and includes concealed pull-out storage for compact homes.", dimensions: "2860(W) × 870(H) × 1620(D) mm; bed depth 2180 mm", material: "Easy-care fabric, steel bed mechanism and high-density foam", colour: "Dove grey", warranty: "5-year structural and 2-year mechanism warranty" },
];
const rooms = [{ name: "Bedroom", image: asset("room-bedroom.png") }, { name: "Living", image: asset("room-living.png") }, { name: "Dining", image: asset("room-dining.png") }, { name: "Office", image: asset("room-office.png") }];
const reviews = [
  { name: "Anna — Melbourne", quote: "Outstanding customer service and faster delivery than expected. The Tribeca sofa feels beautifully made and looks even better in our living room.", image: asset("review-tribeca.png") },
  { name: "Marcus — Geelong", quote: "The Shiloah lounge arrived carefully packed, and the team kept us updated from purchase to delivery. Excellent quality for a busy family home.", image: asset("shiloah.png") },
  { name: "Priya — Sydney", quote: "Helpful advice in store, straightforward checkout and a genuinely comfortable sofa. We would happily shop here again.", image: asset("sonoma.jpg") },
];
const money = (value: number) => `$${value.toLocaleString("en-AU")}`;

export default function Store() {
  const [view, setView] = useState<View>("home");
  const [selectedId, setSelectedId] = useState("shiloah");
  const [listing, setListing] = useState("Living");
  const [query, setQuery] = useState("");
  const [searchOpen, setSearchOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [filterOpen, setFilterOpen] = useState(false);
  const [cart, setCart] = useState<Cart>({});
  const [productQty, setProductQty] = useState(1);
  const [reviewIndex, setReviewIndex] = useState(0);
  const [toast, setToast] = useState("");
  const [lastTotal, setLastTotal] = useState(0);
  const [lastLines, setLastLines] = useState<{ product: Product; quantity: number }[]>([]);
  const selected = products.find((p) => p.id === selectedId) ?? products[0];
  const cartLines = products.filter((p) => cart[p.id]).map((product) => ({ product, quantity: cart[product.id] }));
  const cartCount = cartLines.reduce((sum, line) => sum + line.quantity, 0);
  const cartTotal = cartLines.reduce((sum, line) => sum + line.product.price * line.quantity, 0);
  const suggestions = useMemo(() => (query.trim() ? products.filter((p) => p.name.toLowerCase().includes(query.toLowerCase())) : products).slice(0, 5), [query]);
  const go = (next: View) => { setView(next); setMenuOpen(false); setSearchOpen(false); setFilterOpen(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const openProduct = (id: string) => { setSelectedId(id); setProductQty(1); go("product"); };
  const openListing = (name: string) => { setListing(name); go("listing"); };
  const add = (product: Product, quantity = 1, event?: MouseEvent) => { event?.stopPropagation(); setCart((current) => ({ ...current, [product.id]: (current[product.id] || 0) + quantity })); setToast(`${product.name} added to cart`); window.setTimeout(() => setToast(""), 2400); };
  const setQuantity = (id: string, quantity: number) => setCart((current) => { const next = { ...current }; if (quantity <= 0) delete next[id]; else next[id] = quantity; return next; });
  const submitOrder = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLastTotal(cartTotal); setLastLines(cartLines); setCart({}); go("confirmation"); };
  return <main id="top">
    <Header cartCount={cartCount} query={query} setQuery={setQuery} searchOpen={searchOpen} setSearchOpen={setSearchOpen} menuOpen={menuOpen} setMenuOpen={setMenuOpen} suggestions={suggestions} openProduct={openProduct} openListing={openListing} go={go} />
    {toast && <div className="toast" role="status">✓ {toast}<button onClick={() => go("cart")}>VIEW CART</button></div>}
    {view === "home" && <Home openListing={openListing} openProduct={openProduct} add={add} reviewIndex={reviewIndex} setReviewIndex={setReviewIndex} />}
    {view === "listing" && <Listing title={listing} openProduct={openProduct} add={add} filterOpen={filterOpen} setFilterOpen={setFilterOpen} />}
    {view === "product" && <ProductDetail product={selected} quantity={productQty} setQuantity={setProductQty} add={add} go={go} />}
    {view === "cart" && <CartPage lines={cartLines} total={cartTotal} setQuantity={setQuantity} go={go} />}
    {view === "checkout" && <Checkout lines={cartLines} total={cartTotal} submitOrder={submitOrder} go={go} />}
    {view === "confirmation" && <Confirmation total={lastTotal} lines={lastLines} go={go} />}
    <Footer openListing={openListing} go={go} />
  </main>;
}

function Header({ cartCount, query, setQuery, searchOpen, setSearchOpen, menuOpen, setMenuOpen, suggestions, openProduct, openListing, go }: { cartCount: number; query: string; setQuery: (v: string) => void; searchOpen: boolean; setSearchOpen: (v: boolean) => void; menuOpen: boolean; setMenuOpen: (v: boolean) => void; suggestions: Product[]; openProduct: (id: string) => void; openListing: (name: string) => void; go: (view: View) => void }) {
  return <><div className="announcement">FREE DELIVERY WITH EVERY CUSTOMISED AUSTRALIAN MADE ORDER</div><header className="site-header">
    <button className="logo-button" onClick={() => go("home")} aria-label="My Furniture Store home"><img src={asset("logo.png")} alt="My Furniture Store" /></button>
    <nav className={menuOpen ? "main-nav open" : "main-nav"} aria-label="Primary navigation">{["Living", "Bedroom", "Dining", "Office"].map((name) => <button key={name} onClick={() => openListing(name)}>{name}</button>)}<button className="sale-link" onClick={() => openListing("Sale")}>Sale</button></nav>
    <div className="header-tools"><div className="search-wrap"><label className="search-box"><span>⌕</span><input value={query} onFocus={() => setSearchOpen(true)} onChange={(e) => { setQuery(e.target.value); setSearchOpen(true); }} placeholder="Search furniture" aria-label="Search furniture" /></label>{searchOpen && <div className="search-panel"><div className="search-panel-head"><strong>{query ? "Search results" : "Popular products"}</strong><button onClick={() => setSearchOpen(false)}>×</button></div>{suggestions.map((p) => <button className="search-result" key={p.id} onClick={() => openProduct(p.id)}><img src={p.image} alt="" /><span>{p.name}<b>{money(p.price)}</b></span></button>)}{!suggestions.length && <p>No matching products.</p>}</div>}</div><button className="wishlist" aria-label="Wishlist">♡</button><button className="bag-link" onClick={() => go("cart")}>Bag · {cartCount}</button><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Open menu">☰</button></div>
  </header></>;
}

function Home({ openListing, openProduct, add, reviewIndex, setReviewIndex }: { openListing: (name: string) => void; openProduct: (id: string) => void; add: (p: Product, q?: number, e?: MouseEvent) => void; reviewIndex: number; setReviewIndex: (v: number) => void }) {
  useEffect(() => {
    const timer = window.setInterval(() => setReviewIndex((reviewIndex + 1) % reviews.length), 3000);
    return () => window.clearInterval(timer);
  }, [reviewIndex, setReviewIndex]);
  return <><section className="hero"><div className="hero-copy"><span>AUSTRALIAN MADE</span><h1>Furniture made for<br />the way you live.</h1><p>Warm materials, considered proportions and timeless pieces for every room.</p><div><button className="button brand" onClick={() => openListing("Living")}>SHOP LIVING</button><a className="button surface explore-cta" href="#rooms">EXPLORE COLLECTIONS</a></div></div></section>
  <section className="content-section" id="rooms"><h2>Shop by room</h2><div className="room-grid">{rooms.map((room) => <button className="room-card" key={room.name} onClick={() => openListing(room.name)}><span className="room-image"><img src={room.image} alt={`${room.name} furniture`} /></span><b>{room.name}</b></button>)}</div></section>
  <section className="promo"><button className="promo-copy" onClick={() => openListing("Living")}><small>CUSTOM FURNITURE, MADE LOCALLY</small><strong>EXPLORE</strong><span>→</span><p>Australian-made pieces with complimentary delivery on every customised order.</p></button><img src={asset("promo.png")} alt="Free delivery with every customised Australian made order" /></section>
  <section className="content-section arrivals"><div className="section-title"><div><h2>New arrivals</h2><p>Fresh pieces, familiar warmth.</p></div><button onClick={() => openListing("Living")}>VIEW ALL →</button></div><div className="product-grid">{products.slice(0, 4).map((p, i) => <ProductCard key={p.id} product={p} openProduct={openProduct} add={add} delay={i} />)}</div></section>
  <section className="content-section reviews"><div className="section-title"><div><h2>What our customers say</h2><p>Real homes, considered choices and service people remember.</p></div><span>SWIPE TO EXPLORE →</span></div><div className="review-window"><div className="review-track" style={{ transform: `translateX(-${reviewIndex * 100}%)` }}>{reviews.map((review) => <article className="review-card" key={review.name}><div><div className="stars">★★★★★</div><p>“{review.quote}”</p><strong>{review.name}</strong></div><img src={review.image} alt="Customer furniture" /></article>)}</div></div><div className="review-controls">{reviews.map((r, i) => <button className={reviewIndex === i ? "active" : ""} key={r.name} aria-label={`Show review ${i + 1}`} onClick={() => setReviewIndex(i)} />)}</div></section></>;
}

function Listing({ title, openProduct, add, filterOpen, setFilterOpen }: { title: string; openProduct: (id: string) => void; add: (p: Product, q?: number, e?: MouseEvent) => void; filterOpen: boolean; setFilterOpen: (v: boolean) => void }) {
  const visible = title === "Sale" ? products.filter((p) => p.badge) : title === "Living" || title === "Sofas" ? products.filter((p) => p.category === "Living") : products.filter((p) => p.category === title);
  const hero = title === "Living" ? asset("living-hero.png") : title === "Sofas" || title === "Sale" ? asset("sofa-hero.jpg") : rooms.find((r) => r.name === title)?.image || asset("living-hero.png");
  return <><section className="listing-hero" style={{ backgroundImage: `linear-gradient(rgba(35,31,32,.24),rgba(35,31,32,.24)),url(${hero})` }}><h1>{title}</h1></section><section className="content-section listing"><div className="listing-head"><div><h2>{title === "Living" ? "Living room" : title}</h2><p>{visible.length} featured products</p></div><button className="filter-button" onClick={() => setFilterOpen(!filterOpen)}>FILTER{filterOpen ? " ×" : ""}</button></div>{filterOpen && <div className="filter-panel"><strong>Shop by type</strong>{["All", "Sofas", "Chairs", "Storage", "Sofa beds"].map((item) => <button key={item}>{item}</button>)}<span>In stock · Australian delivery</span></div>}<div className="product-grid listing-grid">{visible.map((p, i) => <ProductCard key={p.id} product={p} openProduct={openProduct} add={add} delay={i} />)}</div></section></>;
}

function ProductCard({ product, openProduct, add, delay = 0 }: { product: Product; openProduct: (id: string) => void; add: (p: Product, q?: number, e?: MouseEvent) => void; delay?: number }) {
  return <article className="product-card" style={{ "--delay": `${delay * 60}ms` } as React.CSSProperties}><button className="card-hit" aria-label={`View ${product.name}`} onClick={() => openProduct(product.id)} /><div className="product-image"><img src={product.image} alt={product.name} />{product.badge && <span>{product.badge}</span>}<b>VIEW PRODUCT</b></div><div className="product-info"><h3>{product.name}</h3><div className="prices"><strong>{money(product.price)}</strong>{product.oldPrice && <del>{money(product.oldPrice)}</del>}</div><small>{product.saving || " "}</small><button onClick={(e) => add(product, 1, e)}>ADD TO CART</button></div></article>;
}

function ProductDetail({ product, quantity, setQuantity, add, go }: { product: Product; quantity: number; setQuantity: (v: number) => void; add: (p: Product, q?: number) => void; go: (view: View) => void }) {
  return <section className="product-page"><div className="product-gallery"><img src={product.image} alt={product.name} /><div className="gallery-dots"><b /><i /><i /><i /></div></div><div className="product-summary"><span className="sale-text">{product.badge || product.category.toUpperCase()}</span><h1>{product.name}</h1><div className="detail-price"><strong>{money(product.price)}</strong>{product.oldPrice && <del>{money(product.oldPrice)}</del>}</div>{product.saving && <p className="saving-text">{product.saving}</p>}<p className="stock">In stock · Delivery calculated at checkout</p><p className="lead">{product.lead}</p><div className="buy-row"><Quantity value={quantity} onChange={setQuantity} /><button className="button brand" onClick={() => add(product, quantity)}>ADD TO CART</button></div><button className="button dark buy-now" onClick={() => { add(product, quantity); go("checkout"); }}>BUY NOW</button><div className="trust-box"><strong>✓ Secure checkout · ↺ Easy returns</strong><span>Australian owned · Customer support</span></div></div><div className="description"><h2>Product description</h2><dl><div><dt>Dimensions</dt><dd>{product.dimensions}</dd></div><div><dt>Colour</dt><dd>{product.colour}</dd></div><div><dt>Material</dt><dd>{product.material}</dd></div><div><dt>Origin</dt><dd>Designed for Australian homes and sourced from trusted furniture makers.</dd></div><div><dt>Warranty</dt><dd>{product.warranty}</dd></div></dl></div><div className="mobile-buy-bar"><strong>{money(product.price)}</strong><button onClick={() => add(product, quantity)}>ADD TO CART</button></div></section>;
}

function Quantity({ value, onChange }: { value: number; onChange: (v: number) => void }) { return <div className="quantity"><button aria-label="Decrease quantity" onClick={() => onChange(Math.max(1, value - 1))}>−</button><span>{value}</span><button aria-label="Increase quantity" onClick={() => onChange(value + 1)}>+</button></div>; }

function CartPage({ lines, total, setQuantity, go }: { lines: { product: Product; quantity: number }[]; total: number; setQuantity: (id: string, q: number) => void; go: (view: View) => void }) {
  return <section className="commerce-page"><div className="page-heading"><h1>Your cart</h1><p>{lines.reduce((s, l) => s + l.quantity, 0)} items</p></div>{!lines.length ? <div className="empty-cart"><h2>Your cart is empty</h2><p>Explore considered pieces for every room.</p><button className="button brand" onClick={() => go("home")}>CONTINUE SHOPPING</button></div> : <div className="cart-layout"><div className="cart-lines">{lines.map(({ product, quantity }) => <article className="cart-line" key={product.id}><img src={product.image} alt={product.name} /><div><h2>{product.name}</h2><strong>{money(product.price)}</strong><Quantity value={quantity} onChange={(v) => setQuantity(product.id, v)} /><button className="remove" onClick={() => setQuantity(product.id, 0)}>Remove</button></div></article>)}</div><OrderSummary total={total} checkout={() => go("checkout")} /></div>}</section>;
}
function OrderSummary({ total, checkout }: { total: number; checkout?: () => void }) { return <aside className="order-summary"><h2>Order summary</h2><div><span>Subtotal</span><b>{money(total)}</b></div><div><span>Delivery</span><span>Calculated at checkout</span></div><hr /><div className="total"><strong>Total</strong><strong>{money(total)}</strong></div>{checkout && <button className="button dark" onClick={checkout}>CHECK OUT</button>}</aside>; }

function Checkout({ lines, total, submitOrder, go }: { lines: { product: Product; quantity: number }[]; total: number; submitOrder: (e: FormEvent<HTMLFormElement>) => void; go: (v: View) => void }) {
  if (!lines.length) return <section className="commerce-page"><div className="empty-cart"><h1>Your cart is empty</h1><button className="button brand" onClick={() => go("home")}>RETURN TO STORE</button></div></section>;
  return <section className="checkout-page"><div className="page-heading"><h1>Checkout</h1><p><button onClick={() => go("cart")}>Cart</button> — Details — Payment</p></div><form onSubmit={submitOrder} noValidate className="checkout-layout"><div className="checkout-form"><div className="demo-checkout-note">Demo checkout · details are pre-filled with safe virtual information.</div><h2>Contact</h2><Field label="Email address" type="email" defaultValue="alex.taylor@example.com" autoComplete="email" /><h2>Delivery</h2><div className="field-grid"><Field label="First name" defaultValue="Alex" autoComplete="given-name" /><Field label="Last name" defaultValue="Taylor" autoComplete="family-name" /></div><Field label="Address" defaultValue="18 Collins Street" autoComplete="street-address" /><Field label="Apartment, suite, etc. (optional)" required={false} defaultValue="Apartment 4" /><div className="field-grid three"><Field label="City" defaultValue="Melbourne" autoComplete="address-level2" /><Field label="State/Territory" defaultValue="VIC" autoComplete="address-level1" /><Field label="Postcode" defaultValue="3000" inputMode="numeric" autoComplete="postal-code" /></div><Field label="Phone" type="tel" defaultValue="0400 123 456" autoComplete="tel" /><h2>Payment</h2><div className="payment-box"><strong>Credit card · VISA · Mastercard · Amex · PayPal</strong><Field label="Card number" defaultValue="4242 4242 4242 4242" inputMode="numeric" autoComplete="cc-number" /><div className="field-grid"><Field label="Expiration date (MM / YY)" defaultValue="12 / 30" autoComplete="cc-exp" /><Field label="Security code" defaultValue="123" inputMode="numeric" autoComplete="cc-csc" /></div><label className="checkbox"><input type="checkbox" defaultChecked /> Use shipping address as billing address</label></div><button className="button brand pay-button" type="submit">PAY NOW · {money(total)}</button></div><div><OrderSummary total={total} /><p className="secure-note">✓ Secure encrypted checkout</p></div></form></section>;
}
function Field({ label, required = true, ...props }: { label: string; required?: boolean; [key: string]: unknown }) { return <label className="field"><span>{label}</span><input aria-label={label} placeholder={label} required={required} {...props} /></label>; }
function Confirmation({ total, lines, go }: { total: number; lines: { product: Product; quantity: number }[]; go: (v: View) => void }) {
  return <section className="confirmation-page"><div className="confirmation-card"><div className="confirmation-success">✓</div><h1>Thank you for your order!</h1><strong className="confirmation-number">Order #MFS-24891</strong><p className="confirmation-email">Your confirmation has been sent to your email address.</p><div className="confirmation-details">{(lines.length ? lines : [{ product: products[0], quantity: 1 }, { product: products[5], quantity: 1 }]).slice(0, 2).map(({ product, quantity }) => <div className="confirmation-line" key={product.id}><img src={product.image} alt={product.name} /><span>{product.name}{quantity > 1 ? ` × ${quantity}` : ""}</span><strong>{money(product.price * quantity)}</strong></div>)}</div><div className="confirmation-total"><span>Total paid</span><strong>{money(total)}</strong></div><button className="button dark" onClick={() => go("home")}>CONTINUE SHOPPING</button></div><h2>What happens next?</h2><div className="next-steps"><article><b>1</b><strong>Confirmation email</strong><span>Sent now</span></article><article><b>2</b><strong>Order preparation</strong><span>We’ll prepare your items</span></article><article><b>3</b><strong>Delivery updates</strong><span>Tracking by email</span></article></div></section>;
}
function Footer({ openListing, go }: { openListing: (n: string) => void; go: (v: View) => void }) { return <footer className="footer"><button className="footer-logo" onClick={() => go("home")}><img src={asset("logo.png")} alt="My Furniture Store" /></button><div className="footer-statement">Furniture made for living.</div><div><b>Shop</b>{["Living", "Bedroom", "Dining", "Office"].map((n) => <button key={n} onClick={() => openListing(n)}>{n}</button>)}</div><div><b>Help</b><a href="#top">Delivery</a><a href="#top">Returns</a><a href="#top">FAQ</a><a href="#top">Contact us</a></div><div><b>Visit</b><a href="#top">Australian made</a><a href="#top">About us</a><a href="#top">Become a customer</a></div><small>© 2026 My Furniture Store · Secure payments · Australian owned · Customer support</small></footer>; }
